<?php

namespace App\Listeners;

use App\Mail\NotifyEmailAboutChangeOrderStatus;
use App\Models\Order;
use Illuminate\Support\Facades\Mail;

class SendEmailNotificationAboutChangeOrderStatus
{
    private Order $order;

    /**
     * Create the event listener.
     */
    public function __construct(Order $order)
    {
        $this->order = $order;
    }


    /**
     * Handles the event triggered when an order status changes.
     *
     * @param object $event The event object containing the order details.
     *
     * @return void
     */
    public function handle(object $event): void
    {
        // Get the email address from the order details in the event.
        $email = $event->order->email;

        // Use Laravel's Mail facade to send an email to the address.
        // The email content is generated by the NotifyEmailAboutChangeOrderStatus Mailable class,
        // which takes the order details as an argument.
        Mail::to($email)->send(new NotifyEmailAboutChangeOrderStatus($event->order));
    }
}
