<?php
return [
    'Smartphone',
    'Tablete',
    'Ceasuri inteligente',
    'Camere Auto',
    'Suporturi pentru telefoane',
    'Boxe Auto',
    'FM-modulatoare',
    'Huse pentru telefoane',
    'Huse pentru tablete',
    'Sticle de protecție',
    'Încărcătoare',
    'Dispozitive inteligente',
    'Televizoare',
    'TV-Boxuri și Media playere',
    'Suporturi TV',
    'Căști',
    'Boxe Portabile',
    'Boxe pentru calculator',
    'Soundbare și Sisteme audio',
    'Microfoane',
    'Frigidere',
    'Plite',
    'Cuptoare Incorporabile',
    'Mașini de Spălat Vase',
    'Hote',
    'Congelatoare',
    'Aragazuri',
    'Vitrine de Vinuri',
    'Tigai și Cratite',
    'Capac din sticla',
    'Termosuri și Căni termos',
    'Prese franceze',
    'Ceainice',
    'Forme de copt',
    'Cutii Aliemntare',
    'Ustensile de bucătărie',
    'Cuțite de bucătărie',
    'Sticle de apă',
    "Cuptoare cu microunde",
    "Multifierbătoare",
    "Blendere",
    "Mixere",
    "Roboți de bucătărie",
    "Friteuze",
    "Grătare electrice",
    "Mașini de copt pâine",
    "Toaster",
    "Aparate pentru sandwich-uri și vafe",
    "Uscătoare de fructe și legume",
    "Storcătoare de fructe",
    "Mașini de tocat carne",
    "Feliatoare",
    "Fierbători electrice",
    "Thermopot",
    "Cuptoare Electrice",
    "Plite de masă",
    "Cântare de bucătărie",
    "Genți frigorifice",
    "Aparate de cafea",
    "Râșnițe de cafea",
    "Cafetiere gheizer",
    "Cafea",
    "Accesorii pentru aparate de cafea",
    "Aparate de aer condiționat",
    "Încălzitoare",
    "Boilere electrice",
    "Purificatoare și Umidificatoare de aer",
    "Dezumidificatoare de aer",
    "Ventilatoare",
    "Fiare de călcat",
    "Generatoare de abur",
    "Vaporizatoare",
    "Dulapuri cu abur pentru haine",
    "Mese de călcat",
    "Aparate de călcat cu abur",
    "Aspiratoare",
    "Aparate de curățat cu aburi",
    "Aparate spălat cu presiune",
    "Ștergătoare și roboți pentru curățarea geamurilor",
    "Mopuri și Mături Electrice",
    "Accesorii pentru aspiratoare",
    "Mașini de Spălat Rufe",
    "Mașini de spălat cu uscător",
    "Uscătoare de rufe",
    "Produse Chimice de Uz Casnic",
    "Uscătoare de păr",
    "Ondulatoare și Plăci de îndreptat părul",
    "Aparate de Tuns",
    "Trimmere",
    "Aparate de ras electrice",
    "Epilatoare",
    "Periuțe de Dinți Electrice",
    "Aparate pentru manichiură și pedichiură",
    "Oglinzi pentru Machiaj",
    "Cântare de podea",
    "Articole Sănătate",
    "Monitoare",
    "Calculatoare",
    "All in One PC",
    "Calculatoare desktop și mini-PC-uri",
    "Mouse-uri",
    "Tastaturi",
    "Mouse pad-uri",
    "Camere web",
    "Impriante",
    "Impriante Multifuncționale",
    "Console Jocuri",
    "Controlere Gaming",
    "Jocuri Consolă și PC",
    "Căști Gaming",
    "Scaune Gaming",
    "Birouri Gaming",
    "Mouse pad-uri Gaming",
    "Mașinuțe electrice pentru copii",
    "Trotinete electrice",
    "Biciclete pentru copii",
    "Triciclete pentru copii",
    "Trotinete electrice",
    "Cărucioare pentru copii",
    "Scaune auto pentru copii",
    "Scăunele pentru hrănire",
    "Saltele gonflabile",
    "Topogane pentru copii",
    "Trambuline",
    "Piscine",
    
];
