version: '3.8'

services:
    proxi:
        image: traefik:v3.0
        restart: always
        container_name: traefik
        ports: 
            - 80:80
            - 8080:8080
            #- 443:443
        command: 
            - --api.insecure=true
            - --api.dashboard=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --providers.docker.network=traff
            
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            #- ./traefik.toml:/traefik.toml
            # - /traefik_dynamic.toml:/traefik_dynamic.toml
            #- ./acme.json:/acme.json
        networks: 
            - traff

networks:
    traff:
        name: traff
