<?php

namespace App\Providers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Blade::directive('tr', function ($expression) {
            return "<?php echo __($expression); ?>";
        });
        /** Force https for secure connections generated by functions: url() and route() **/
        if (in_array(env('APP_ENV'), ['stg', 'production'])) {
            URL::forceScheme('https');

            //this setting was forcing to https the links generated by the paginator; otherwise not changed by forceScheme
            $this->app['request']->server->set('HTTPS', 'on');
        }
        DB::listen(function ($query) {
            if (strpos($query->sql, 'products') !== false) { // Doar interogările care includ "users"
                Log::channel('queries')->info('Executed query', [
                    'sql' => $query->sql,
                    'bindings' => $query->bindings,
                    'time' => $query->time,
                ]);
            }
        });
    }
}
